# Generated by Django 2.2.5 on 2019-11-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_student_gpa_projected'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_section',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='class_teacher_number',
            field=models.IntegerField(null=True),
        ),
    ]
