# Generated by Django 2.2.5 on 2019-11-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191125_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='missing_submissions_names',
        ),
        migrations.CreateModel(
            name='ContentGrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50, null=True)),
                ('grade_letter', models.CharField(max_length=50, null=True)),
                ('grade_number', models.CharField(max_length=50, null=True)),
                ('content_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Content')),
            ],
        ),
    ]
