# Generated by Django 2.2.5 on 2019-11-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191125_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='affect',
            field=models.IntegerField(null=True),
        ),
    ]
